Repository dusk-network/wallet-cli, pull requests merged in 2022-08, with the labels that each got.

#61 Create a library for the Dusk wallet
  .gitignore
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  src/bin/command.rs
  src/bin/error.rs
  src/bin/execute.rs
  src/bin/interactive.rs
  src/bin/io/args.rs
  src/bin/io/config.rs
  src/bin/io/gql.rs
  src/bin/io/mod.rs
  src/bin/io/prompt.rs
  src/bin/io/status.rs
  src/bin/io/store.rs
  src/bin/main.rs
  src/bin/menu.rs
  src/bin/wallet.rs
  src/block.rs
  src/cache.rs
  src/clients.rs
  src/crypto.rs
  src/dusk.rs
  src/error.rs
  src/lib.rs
  src/rusk.rs
  src/store.rs
  src/wallet.rs
Labels: area:wallet

#62 Setup proper logging capabilities
  CHANGELOG.md
  Cargo.toml
  README.md
  config.toml
  src/bin/command.rs
  src/bin/error.rs
  src/bin/interactive.rs
  src/bin/io/args.rs
  src/bin/io/config.rs
  src/bin/io/mod.rs
  src/bin/io/status.rs
  src/bin/main.rs
Labels: area:wallet

#69 Windows terminal compatibility
  CHANGELOG.md
  Cargo.toml
  src/bin/main.rs
Labels: fix:bug, mark:testnet, module:rusk-wallet

#76 Release v0.11.1
  CHANGELOG.md
  Cargo.toml
Labels: area:wallet, mark:testnet
